version: '3'
services:
  webphp:
    image: edersondev/php7
    ports:
      - "80:80"
    volumes:
      - ~/Desktop/projetos/vanhackathon230618/review_syncer:/var/www/html
    links:
     - db:mysql
    environment:
      WEB_DOCUMENT_ROOT: public

  db:
    image: mysql:5.7
    restart: always
    volumes:
     - /var/lib/mysql
    environment:
     MYSQL_DATABASE: bold_reviews
     MYSQL_ROOT_PASSWORD: supersecret
     MYSQL_ROOT_HOST: 172.*.*.*

  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1