version: '3'
services:
  webphp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "85:80"
    volumes:
      - /home/gmaciel/docker/bold/review_syncer:/var/www/html
    links:
     - db:mysql
    environment:
      WEB_DOCUMENT_ROOT: public

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - /var/lib/mysql
    environment:
     MYSQL_DATABASE: bold_reviews
     MYSQL_ROOT_PASSWORD: builders
     MYSQL_ROOT_HOST: "%"

  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 86:80
    environment:
      - PMA_ARBITRARY=1
